reddit_on_rails/config/routes.rb
Rails.application.routes.draw do

  resources :comments, only: [:edit, :update, :destroy]

  resources :posts, only: [:edit, :update, :destroy, :show] do
    resources :comments, only: [:new, :create]
  end

  resources :users do
    resources :subs, only: [:edit, :update]
  end

  resource :session

  resources :subs, only: [:new, :create, :index, :show] do
    resources :posts, only: [:new, :create]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

reddit_on_rails/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  sub_id     :integer          not null
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true

  belongs_to :sub

  belongs_to :author,
  foreign_key: :author_id,
  class_name: :User

  has_many :post_subs, inverse_of: :post

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments

end

reddit_on_rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_login
  before_action :require_author, only: [:edit, :update]

  def new
    @post = Post.new
    @post.sub_id = params[:sub_id]
  end

  def create
    # params = {:title: "Tommy", :url, :content, sub_ids: []}

    @post = Post.new(post_params)
    # post = Post.new
    # post.title=("Tommy")
    # post.sub_ids = ["", "1", "2"]
    # @post = current_user.posts.new(post_params)

    @post.author_id = current_user.id
    @post.sub_id = params[:sub_id]

    # @post.post_subs.each do |ps|
    #   ps.save
    #   ps.post_id
    #   ps.post
    # end
    # ps = @post.post_subs.new
    # ps.post #=> @post

    if @post.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to sub_url(@post.sub)
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

reddit_on_rails/app/helpers/posts_helper.rb
module PostsHelper
end

reddit_on_rails/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

reddit_on_rails/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

reddit_on_rails/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label>

  <label>Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label>

  <input type="submit" name="submit" value="Update Post">

</form>

reddit_on_rails/app/views/posts/new.html.erb
<h1>Create Post</h1>


<form action="<%= sub_posts_url(@post.sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="post[title]" value="">
  </label>

  <label>URL
    <input type="text" name="post[url]" value="">
  </label>

  <label>Content
    <input type="text" name="post[content]" value="">
  </label>
  <br>
  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |sub| %>
    <label>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>>
        <%= sub.title %>
    </label>
    <br>
  <% end %>

  <input type="submit" name="submit" value="Create Post">

</form>

reddit_on_rails/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.url %></p>
<p><%= @post.content %></p>

<%= link_to 'Edit Post', edit_post_url(@post) %>

<h2>Add Comment</h2>
<form action="<%= post_comments_url(@post) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Content
    <input type="text" name="comment[content]" value="">
  </label>

  <input type="submit" value="Add Comment">
</form>

<% @post.comments.each do |comment| %>
  <%= comment.content %>
  <%= button_to 'Delete Comment', comment_url(comment), method: :delete %>

  <p>Reply</p>
  <form action="<%= post_comments_url(@post) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Content
      <input type="text" name="comment[content]" value="">
    </label>

    <input type="submit" value="reply">
  </form>
  <% comment.comments.each do |reply| %>
    <%= reply.content %>
    <%= button_to 'Delete Reply', comment_url(reply), method: :delete %>
  <% end %>
  <br>
  <br>
<% end %>

reddit_on_rails/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>