reddit_on_rails/config/routes.rb
Rails.application.routes.draw do

  resources :comments, only: [:edit, :update, :destroy]

  resources :posts, only: [:edit, :update, :destroy, :show] do
    resources :comments, only: [:new, :create]
  end

  resources :users do
    resources :subs, only: [:edit, :update]
  end

  resource :session

  resources :subs, only: [:new, :create, :index, :show] do
    resources :posts, only: [:new, :create]
  end



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

reddit_on_rails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string
#  description  :string
#  moderator_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: :User

  has_many :posts

  has_many :post_subs

end

reddit_on_rails/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_login
  before_action :require_moderator, only: [:edit, :update]

  def new
    @sub = Sub.new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def edit
    @sub = current_user.subs.find(params[:id])
  end

  def update
    @sub = current_user.subs.find(params[:id])

    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index
    @subs = Sub.all
  end

  def show
    @sub = Sub.find(params[:id])
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

reddit_on_rails/app/helpers/subs_helper.rb
module SubsHelper
end

reddit_on_rails/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

reddit_on_rails/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>


<form action="<%= user_sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">

  <label>Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>

  <input type="submit" name="submit" value="Create">

</form>

reddit_on_rails/app/views/subs/index.html.erb
<h1>All Subs</h1>

<% @subs.each do |sub| %>
  <%= link_to sub.title, sub_url(sub) %>
  <%= sub.description %>
  <br>
<% end %>

<%= link_to 'New Sub', new_sub_url %>

reddit_on_rails/app/views/subs/new.html.erb
<h1>Create Sub</h1>


<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Title
    <input type="text" name="sub[title]" value="">
  </label>

  <label>Description
    <input type="text" name="sub[description]" value="">
  </label>

  <input type="submit" name="submit" value="Create">

</form>

reddit_on_rails/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<p><%= @sub.description %></p>

<%= link_to 'Edit Sub', edit_user_sub_url(@sub) %>
<%= link_to 'Add Post', new_sub_post_url(@sub) %>
<br>

<% @sub.posts.each do |post| %>
  <ul>
    <%= link_to post.title, post_url(post) %>
    <% if current_user.id == post.author_id %>
      <%= button_to "Delete Post", post_url(post), method: :delete %>
    <% end %>
  </ul>
<% end %>

reddit_on_rails/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>